#!/bin/bash -xeE
#
# Copyright 2022 Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"). You may not use 
# this file except in compliance with the License. A copy of the License is located at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# or in the "license" file accompanying this file. This file is distributed on an "AS IS" 
# BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the 
# License for the specific language governing permissions and limitations under the License.
#

# This runs as an ec2-user

# Go $HOME
cd ~

# Build executable
unzip /tmp/f1telem.zip -d ~/f1telem
cd ~/f1telem
go build .
sudo cp /tmp/f1telem.service /etc/systemd/system/f1telem.service
sudo chmod 755 /etc/systemd/system/f1telem.service
sudo systemctl enable f1telem.service
sudo systemctl start f1telem.service
# modify code for syslog - https://fabianlee.org/2017/05/21/golang-running-a-go-binary-as-a-systemd-service-on-ubuntu-16-04/
