#!/bin/bash -xeE
#
# Copyright 2022 Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"). You may not use 
# this file except in compliance with the License. A copy of the License is located at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# or in the "license" file accompanying this file. This file is distributed on an "AS IS" 
# BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the 
# License for the specific language governing permissions and limitations under the License.
#

# if the script fails at any point - signal (which will fast-fail the cloudformation deployment)
function signal-fail {
    echo "Failed"
    /opt/aws/bin/cfn-signal --success=false --resource=$AUTO_SCALING_GROUP --stack=$STACK_NAME --region=$REGION
}
trap 'signal-fail' ERR

# yum may still be running, sleep a bit before calling it
yum upgrade
yum install -y golang